services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - database

  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: "python consumer.py"
  #   depends_on:
  #     - database

  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: 20194616
      MYSQL_ROOT_PASSWORD: 20194616
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306